In [1]:
a = 5
b = 10

a,b=b,a
print(a,b)

10 5


In [2]:
b

5

In [3]:
a

10

In [8]:
num =[10,20,33,44,55]
print(min(num))

10


In [9]:
import numpy as np

In [10]:
arr =np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [12]:
print(np.zeros((2,3)))
print(np.zeros((2,2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]
 [0. 0.]]


In [13]:
a=np.array([1,22,33])
b=np.array([33,55,66])
print(a+b)

[34 77 99]


In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)

[5 7 9]


In [15]:
arr = np.array([10,22,44])
print(np.mean(arr))

25.333333333333332


In [16]:
arr = np.array([10, 20, 30])

print(np.mean(arr))

20.0


In [20]:
arr=np.array([10,20,33,40,50])
print(arr[2:3:4])

[33]


In [22]:
arr=np.array([11,22,33,44,55,66])
print(arr.reshape(2,3))

[[11 22 33]
 [44 55 66]]
